export const shippingData = [
  {
    "title": "United States of America - Not Supported",
    "shipsTo": [
      "Alabama",
      "Alaska",
      "American Samoa",
      "Arkansas",
      "Delaware",
      "District of Columbia",
      "Georgia",
      "Iowa",
      "Kentucky",
      "Michigan",
      "Mississippi",
      "New Hampshire",
      "Northern Mariana Islands",
      "Puerto Rico",
      "Utah",
      "Virgin Islands",
      "Armed Forces Africa",
      "Armed Forces Americas (except Canada)",
      "Armed Forces Canada",
      "Armed Forces Europe",
      "Armed Forces Middle East",
      "Armed Forces Pacific"
    ]
  },
  {
    "title": "United States of America - Supported",
    "shipsTo": [
      "Arizona",
      "California",
      "Colorado",
      "Connecticut",
      "Federated States of Micronesia",
      "Florida",
      "Guam",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Kansas",
      "Louisiana",
      "Maine",
      "Marshall Islands",
      "Maryland",
      "Massachusetts",
      "Minnesota",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Palau",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming"
    ]
  },
  {
    "title": "Countries we cannot ship to",
    "shipsTo": [
      "Aaland Islands",
      "Antarctica",
      "Argentina",
      "Bahrain",
      "Bangladesh",
      "Belarus",
      "Bosnia And Herzegovina",
      "Botswana",
      "Bouvet Island",
      "Brazil",
      "Brunei Darussalam",
      "Bulgaria",
      "Cambodia",
      "Cocos (Keeling) Islands",
      "Colombia",
      "Comoros",
      "Congo, Republic Of",
      "Cote D'ivoire",
      "Cuba",
      "Ecuador",
      "Egypt",
      "French Southern Territories",
      "Georgia",
      "Guinea-Bissau",
      "Haiti",
      "Heard and Mc Donald Islands",
      "India",
      "Indonesia",
      "Iran (Islamic Republic Of)",
      "Iraq",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Korea, Democratic People's Republic Of",
      "Kuwait",
      "Liberia",
      "Lithuania",
      "Macedonia, The Former Yugoslav Republic Of",
      "Mexico",
      "Montenegro",
      "Myanmar",
      "Nepal",
      "Netherlands Antilles",
      "Niue",
      "Oman",
      "Pakistan",
      "Philippines",
      "Pitcairn",
      "Puerto Rico",
      "Qatar",
      "Russian Federation",
      "Rwanda",
      "Saint Helena",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Somalia",
      "South Georgia and the South Sandwich Islands",
      "Sudan",
      "Svalbard and Jan Mayen Islands",
      "Syrian Arab Republic",
      "Thailand",
      "Tokelau",
      "Trinidad And Tobago",
      "Turkey",
      "Turkmenistan",
      "Ukraine",
      "United Arab Emirates",
      "United States Minor Outlying Islands",
      "Uruguay",
      "Vietnam",
      "Virgin Islands (U.S.)",
      "Wallis And Futuna Islands",
      "Western Sahara"
    ]
  },
  {
    "title": "Countries we can ship to",
    "shipsTo": ["All the ones not mentioned before"],
    "open": true
  }
];
